import React from "react";
import Head from "next/head";

const HeadPage =()=>{

    return(
        <>
        <Head>
       <section>
<title>Research Paper</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" />
<link href="/assets/css/Research-custom.css" rel="stylesheet"/></section>
</Head>
        </>
    )
}
export default HeadPage
